name: 'size-limit'

on:
  pull_request:
    branches:
      - master

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn --silent

      - uses: andresz1/size-limit-action@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
